[appearance]
prefer_no_csd = true
border_width = 2
corner_radius = 10
drag_opacity = 0.75

[appearance.blur]
enabled = false
optimized = true
passes = 3
radius = 5
noise = 0.02
brightness = 0.9
contrast = 0.9
saturation = 1.1

[appearance.shadow]
enabled = true
softness = 10
offset_x = 2
offset_y = 2

[animation]
enabled = true
duration_ms = 250
curve = "easeout"
